### ISSUE TITLE
No name attribute in APN:App

### ISSUE THREAD

**Issue by twigbranch** [PRX/apn_on_rails#16]
I may be missing something, but I don't see a 'name' attribute in APN:App, yet it appears in the example of the readme.  Some sort of app identifier, whether it be the bundle name, or the bundle id would be useful.

**Comment by rebeccanesson** [comment]
You are right.  Name is a field that I added in a subclass in the implementation I used as an example when creating the readme.

I'm not sure whether to incorporate it into the APN::App model assuming, as you suggest, that it will be useful to others or whether to update the readme to remove it.

**Comment by cwoloszynski** [comment]
Can you make the 'name' field part of the system and release it?  I suspect that most of us using this GEM will need to look up the App instance when creating new devices and we don't want to embed the ID of the app instance into our code.  The name field allows us to look up the right instance without concern for the state of the ID.

I guess I am asking for this since I don't know how to alter a GEM object's structure to add new fields like this.

**Comment by rebeccanesson** [comment]
Hi, 

Thanks for your input on this.  We'll make this change the next time we update the gem.  In the meantime, you can create a subclass of the APN::App class that includes a name field.  

Best, Rebecca
