### ISSUE TITLE
Enhanced Binary Format

### ISSUE THREAD

**Issue by dav** [PRX/apn_on_rails#19]
It appears from a glance at the source for Notification#message_for_sending that this code does not support the Enhanced Binary Format for APNs. Is this correct?

Ref: http://developer.apple.com/library/ios/#documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingWIthAPS/CommunicatingWIthAPS.html#//apple_ref/doc/uid/TP40008194-CH101-SW4

**Comment by rebeccanesson** [comment]
To be honest, I'm not sure about this.  The message_for_sending code is part of the gem that comes from the Mark Bates version that pre-dates when we took it over.  If you'd like to look further into it and perhaps submit a patch, that would be great.  Otherwise I'll take a look when we do our next round of substantial revisions.

**Comment by dav** [comment]
Someone has already worked on it:

https://github.com/greg-barnett/apn_on_rails/tree/enhanced_notification_format

I manually patched an older fork of apn_on_rails with some of that code today. It works ok, although I changed a few things. I'll be using apn_on_rails in a green field project soon, so I'll try forking your master then and applying the greg-barnett code with my changes to that and let you know.
